"""Shared test fixtures for dna-rag."""

from __future__ import annotations

from pathlib import Path

import pytest

from dna_rag.cache.memory import InMemoryCache
from dna_rag.config import Settings

# ---------------------------------------------------------------------------
# FakeLLMProvider -- deterministic stub implementing the LLMProvider protocol
# ---------------------------------------------------------------------------


class FakeLLMProvider:
    """Deterministic LLM provider for testing.

    Returns responses from a pre-configured list in order.
    Records every prompt it receives for assertion.
    """

    def __init__(self, responses: list[str]) -> None:
        self.responses = responses
        self.calls: list[str] = []
        self._index = 0

    def invoke(self, prompt: str) -> str:
        self.calls.append(prompt)
        if self._index < len(self.responses):
            response = self.responses[self._index]
            self._index += 1
            return response
        return ""


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture(autouse=True)
def reset_chromadb():
    """Reset ChromaDB singleton between tests to avoid settings conflicts."""
    yield
    # Clean up ChromaDB singleton after each test
    try:
        import chromadb.api.client

        # Clear the internal singleton dictionary
        chromadb.api.client.SharedSystemClient._identifer_to_system = {}
    except (ImportError, AttributeError):
        pass


@pytest.fixture
def fake_llm():
    """Factory fixture for creating :class:`FakeLLMProvider`."""

    def _factory(responses: list[str]) -> FakeLLMProvider:
        return FakeLLMProvider(responses)

    return _factory


@pytest.fixture
def settings(monkeypatch: pytest.MonkeyPatch) -> Settings:
    """Settings fixture with test defaults."""
    monkeypatch.setenv("DNA_RAG_LLM_API_KEY", "test-key-not-real")
    return Settings(
        llm_provider="deepseek",
        llm_api_key="test-key-not-real",  # type: ignore[arg-type]
        cache_backend="memory",
    )


@pytest.fixture
def cache() -> InMemoryCache:
    """Fresh in-memory cache for each test."""
    return InMemoryCache(max_size=100, ttl_seconds=300)


# ---------------------------------------------------------------------------
# Sample DNA files
# ---------------------------------------------------------------------------


@pytest.fixture
def sample_23andme_file(tmp_path: Path) -> Path:
    """Create a sample 23andMe format DNA file."""
    content = (
        "# This data file generated by 23andMe at ...\n"
        "# rsid\tchromosome\tposition\tgenotype\n"
        "rs1\t1\t111\tAA\n"
        "rs2\t1\t112\tGG\n"
        "rs3\t2\t200\tCT\n"
        "rs4\tX\t500\tAA\n"
    )
    f = tmp_path / "sample_23andme.txt"
    f.write_text(content)
    return f


@pytest.fixture
def sample_myheritage_file(tmp_path: Path) -> Path:
    """Create a sample MyHeritage format DNA file."""
    content = (
        "# MyHeritage DNA raw data\n"
        "RSID,CHROMOSOME,POSITION,RESULT\n"
        "rs1,1,111,AA\n"
        "rs2,1,112,GG\n"
        "rs3,2,200,CT\n"
    )
    f = tmp_path / "sample_myheritage.csv"
    f.write_text(content)
    return f


@pytest.fixture
def sample_ancestrydna_file(tmp_path: Path) -> Path:
    """Create a sample AncestryDNA format DNA file."""
    content = (
        "#AncestryDNA raw data download\n"
        "#rsid\tchromosome\tposition\tallele1\tallele2\n"
        "rs1\t1\t111\tA\tA\n"
        "rs2\t1\t112\tG\tG\n"
        "rs3\t2\t200\tC\tT\n"
    )
    f = tmp_path / "sample_ancestrydna.txt"
    f.write_text(content)
    return f


@pytest.fixture
def sample_csv_file(tmp_path: Path) -> Path:
    """Simple headerless CSV for backward-compatibility tests."""
    data = "rs1,1,111,AA\nrs2,1,112,GG\n"
    f = tmp_path / "dna.csv"
    f.write_text(data)
    return f
