"""Shared fixtures for API tests.

Creates a FastAPI TestClient with a mocked engine (using FakeLLMProvider)
so tests don't need a real LLM key.
"""

from __future__ import annotations

import io
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from dna_rag.api.config import APISettings
from dna_rag.api.main import create_app
from dna_rag.api.services.files import FileService
from dna_rag.cache.memory import InMemoryCache
from dna_rag.engine import DNAAnalysisEngine

# Re-use FakeLLMProvider from the main conftest
from tests.conftest import FakeLLMProvider

# ---------------------------------------------------------------------------
# Standard LLM responses for a complete pipeline run
# ---------------------------------------------------------------------------

SNP_JSON = """{
  "rs1": {
    "gene": "TEST_GENE",
    "chromosome": "1",
    "position": 111,
    "trait": "Test trait"
  }
}"""

INTERPRETATION = "Based on your genotype AA at rs1, you have the test trait."


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture()
def api_settings(tmp_path: Path) -> APISettings:
    """APISettings with test defaults (no real LLM key needed)."""
    return APISettings(
        llm_api_key="test-key",  # type: ignore[arg-type]
        llm_provider="deepseek",
        cache_backend="memory",
        cache_max_size=100,
        cache_ttl_seconds=300,
        auth_enabled=False,
        upload_dir=str(tmp_path / "uploads"),
        rate_limit_per_minute=1000,
        log_level="WARNING",
    )


@pytest.fixture()
def fake_engine() -> DNAAnalysisEngine:
    """Engine wired with a FakeLLMProvider."""
    llm = FakeLLMProvider([SNP_JSON, INTERPRETATION])
    cache = InMemoryCache(max_size=100, ttl_seconds=300)
    return DNAAnalysisEngine(snp_llm=llm, cache=cache)


@pytest.fixture()
def file_service(tmp_path: Path) -> FileService:
    """FileService pointed at a temp directory."""
    return FileService(
        upload_dir=str(tmp_path / "uploads"),
        max_size_mb=10,
    )


@pytest.fixture()
def client(
    api_settings: APISettings,
    fake_engine: DNAAnalysisEngine,
    file_service: FileService,
) -> TestClient:
    """TestClient with mocked dependencies."""
    app = create_app(settings=api_settings)

    # Override DI to use our fake engine and file service
    from dna_rag.api import dependencies
    from dna_rag.api.services.analysis import AnalysisService
    from dna_rag.api.services.jobs import JobStore

    analysis_service = AnalysisService(
        engine=fake_engine,
        file_service=file_service,
        settings=api_settings,
    )
    job_store = JobStore(ttl_seconds=3600)

    app.dependency_overrides[dependencies.get_analysis_service] = lambda: analysis_service
    app.dependency_overrides[dependencies.get_file_service] = lambda: file_service
    app.dependency_overrides[dependencies.get_job_store] = lambda: job_store
    app.dependency_overrides[dependencies.get_engine] = lambda: fake_engine

    return TestClient(app)


@pytest.fixture()
def sample_dna_bytes() -> bytes:
    """Raw bytes of a valid 23andMe DNA file."""
    return (
        b"# This data file generated by 23andMe\n"
        b"# rsid\tchromosome\tposition\tgenotype\n"
        b"rs1\t1\t111\tAA\n"
        b"rs2\t1\t112\tGG\n"
        b"rs3\t2\t200\tCT\n"
    )


@pytest.fixture()
def uploaded_file_id(client: TestClient, sample_dna_bytes: bytes) -> str:
    """Upload a sample file and return its file_id."""
    resp = client.post(
        "/api/v1/files",
        files={"file": ("sample.txt", io.BytesIO(sample_dna_bytes), "text/plain")},
    )
    assert resp.status_code == 201
    return resp.json()["file_id"]
