"""Parser for 23andMe raw data exports.

23andMe files are tab-separated with comment lines starting with ``#``::

    # This data file generated by 23andMe at ...
    # rsid  chromosome  position  genotype
    rs12345  1  12345  AG
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
from pandas import DataFrame

from dna_rag.exceptions import InvalidDNAFileError
from dna_rag.logging import get_logger

logger = get_logger(__name__)

_MARKER = "23andme"


class TwentyThreeAndMeParser:
    """Parser for 23andMe raw DNA data files."""

    @staticmethod
    def can_parse(file_path: Path) -> bool:
        """Detect by checking for ``23andMe`` in header comments."""
        try:
            with file_path.open(encoding="utf-8", errors="replace") as fh:
                for line in fh:
                    if not line.startswith("#"):
                        # Check if first data line is tab-separated with 4 fields
                        parts = line.strip().split("\t")
                        return len(parts) == 4 and parts[0].lower().startswith("rs")
                    if _MARKER in line.lower():
                        return True
        except OSError:
            return False
        return False

    @staticmethod
    def parse(file_path: Path) -> DataFrame:
        """Parse a 23andMe raw data file.

        Returns:
            Standardised DataFrame with columns
            ``RSID``, ``CHROMOSOME``, ``POSITION``, ``GENOTYPE``.

        Raises:
            InvalidDNAFileError: File cannot be parsed.
        """
        try:
            df = pd.read_csv(
                file_path,
                comment="#",
                delimiter="\t",
                header=None,
                names=["RSID", "CHROMOSOME", "POSITION", "GENOTYPE"],
                dtype={"RSID": str, "CHROMOSOME": str, "GENOTYPE": str},
            )
        except Exception as exc:
            raise InvalidDNAFileError(
                f"Failed to parse 23andMe file {file_path}: {exc}"
            ) from exc

        if df.empty:
            logger.warning("empty_dna_file", parser="23andMe", file=str(file_path))
            return _empty_frame()

        df["RSID"] = df["RSID"].str.strip().str.lower()
        df["CHROMOSOME"] = df["CHROMOSOME"].str.strip().str.upper()
        df["GENOTYPE"] = df["GENOTYPE"].str.strip().str.upper()
        df["POSITION"] = pd.to_numeric(df["POSITION"], errors="coerce").fillna(0).astype(int)

        logger.info("parsed", parser="23andMe", rows=len(df))
        return df


def _empty_frame() -> DataFrame:
    return DataFrame(columns=["RSID", "CHROMOSOME", "POSITION", "GENOTYPE"])
