"""FastAPI application for DNA RAG."""

from __future__ import annotations

import io
import logging
from contextlib import asynccontextmanager
from typing import Any, AsyncIterator

import pandas as pd
from fastapi import FastAPI, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware

from dna_rag.core.chat_dna import ChatDNA
from dna_rag.core.chat_dna_enhanced import ChatDNAEnhanced
from dna_rag.core.config import get_settings
from dna_rag.models.api_models import (
    DNAQuestionRequest,
    DNAQuestionResponse,
    EnhancedDNAQuestionResponse,
    ErrorResponse,
    HealthCheckResponse,
    PolygenicScoreRequest,
    PolygenicScoreResponse,
    SNPResult,
)
from dna_rag.utils.polygenic_scores import PolygenicScoreCalculator

logger = logging.getLogger(__name__)

# Global instances
chat_dna: ChatDNA | None = None
chat_dna_enhanced: ChatDNAEnhanced | None = None
settings = get_settings()


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncIterator[None]:
    """Application lifespan manager."""
    global chat_dna, chat_dna_enhanced

    # Validate API keys
    try:
        settings.validate_api_keys()
    except ValueError as e:
        logger.error(f"API key validation failed: {e}")
        raise

    # Initialize ChatDNA instances
    api_key = settings.deepseek_api_key or settings.openai_api_key
    chat_dna = ChatDNA(api_key)
    chat_dna_enhanced = ChatDNAEnhanced(api_key)

    logger.info("DNA RAG API started successfully")
    yield

    # Cleanup
    logger.info("DNA RAG API shutting down")


app = FastAPI(
    title="DNA RAG API",
    description="API for analyzing DNA data using language models with RAG",
    version="0.1.0",
    lifespan=lifespan,
)

# Add CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get(
    "/health",
    response_model=HealthCheckResponse,
    summary="Health check endpoint",
)
async def health_check() -> HealthCheckResponse:
    """Check API health and configuration."""
    providers_status: dict[str, Any] = {}

    if settings.openai_api_key:
        providers_status["openai"] = {
            "available": True,
            "model": settings.openai_model,
        }
    if settings.deepseek_api_key:
        providers_status["deepseek"] = {
            "available": True,
            "model": settings.deepseek_model,
        }

    return HealthCheckResponse(
        status="healthy",
        version="0.1.0",
        providers=providers_status,
    )


@app.post(
    "/ask",
    response_model=DNAQuestionResponse,
    summary="Ask a question about DNA data",
    responses={
        400: {"model": ErrorResponse},
        500: {"model": ErrorResponse},
    },
)
async def ask_dna_question(request: DNAQuestionRequest) -> DNAQuestionResponse:
    """Ask a question about DNA data.

    This endpoint accepts DNA data in CSV format and a question, then returns
    an answer generated by the language model.

    Parameters
    ----------
    request : DNAQuestionRequest
        Request containing the question and DNA data

    Returns
    -------
    DNAQuestionResponse
        Answer to the question

    Raises
    ------
    HTTPException
        If DNA data parsing fails or LLM query fails
    """
    if chat_dna is None:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Service not initialized",
        )

    try:
        # Parse DNA data from CSV string
        dna_df = pd.read_csv(io.StringIO(request.dna_data))

        # Validate DNA data format
        required_columns = ["rsid", "chromosome", "position", "genotype"]
        if not all(col in dna_df.columns for col in required_columns):
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"DNA data must contain columns: {required_columns}",
            )

        # Save to temporary file for ChatDNA
        temp_path = "/tmp/dna_temp.csv"
        dna_df.to_csv(temp_path, index=False)

        # Get answer
        answer = chat_dna.ask(request.question, temp_path)

        return DNAQuestionResponse(
            question=request.question,
            answer=answer,
            provider="deepseek",  # TODO: get actual provider from ChatDNA
        )

    except pd.errors.ParserError as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Failed to parse DNA data: {str(e)}",
        )
    except Exception as e:
        logger.error(f"Error processing DNA question: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error processing request: {str(e)}",
        )


@app.post(
    "/ask-enhanced",
    response_model=EnhancedDNAQuestionResponse,
    summary="Ask a question with enhanced features (RAG, validation)",
    responses={
        400: {"model": ErrorResponse},
        500: {"model": ErrorResponse},
    },
)
async def ask_dna_question_enhanced(
    request: DNAQuestionRequest,
) -> EnhancedDNAQuestionResponse:
    """Ask a question about DNA data with enhanced features.

    This endpoint uses RAG (Retrieval-Augmented Generation), SNP validation,
    and returns structured output with confidence scores and source citations.

    Parameters
    ----------
    request : DNAQuestionRequest
        Request containing the question and DNA data

    Returns
    -------
    EnhancedDNAQuestionResponse
        Structured answer with metadata

    Raises
    ------
    HTTPException
        If DNA data parsing fails or LLM query fails
    """
    if chat_dna_enhanced is None:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Service not initialized",
        )

    try:
        # Parse DNA data from CSV string
        dna_df = pd.read_csv(io.StringIO(request.dna_data))

        # Validate DNA data format
        required_columns = ["rsid", "chromosome", "position", "genotype"]
        if not all(col in dna_df.columns for col in required_columns):
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"DNA data must contain columns: {required_columns}",
            )

        # Save to temporary file for ChatDNAEnhanced
        temp_path = "/tmp/dna_temp.csv"
        dna_df.to_csv(temp_path, index=False)

        # Get enhanced answer
        result = chat_dna_enhanced.ask(request.question, temp_path)

        # Convert to API response format
        snps_found = [
            SNPResult(
                rsid=snp.rsid,
                genotype=snp.genotype,
                gene=snp.gene,
                trait=snp.trait,
                validated=snp.validated,
                similarity=snp.similarity,
            )
            for snp in result.snps_found
        ]

        return EnhancedDNAQuestionResponse(
            question=result.question,
            interpretation=result.interpretation,
            confidence=result.confidence,
            snps_found=snps_found,
            sources=result.sources,
            caveats=result.caveats,
            provider="deepseek",  # TODO: get actual provider
        )

    except pd.errors.ParserError as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Failed to parse DNA data: {str(e)}",
        )
    except Exception as e:
        logger.error(f"Error processing enhanced DNA question: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error processing request: {str(e)}",
        )


@app.post(
    "/polygenic-score",
    response_model=PolygenicScoreResponse,
    summary="Calculate polygenic risk score",
    responses={
        400: {"model": ErrorResponse},
        500: {"model": ErrorResponse},
    },
)
async def calculate_polygenic_score(
    request: PolygenicScoreRequest,
) -> PolygenicScoreResponse:
    """Calculate a polygenic risk score.

    Parameters
    ----------
    request : PolygenicScoreRequest
        Request containing score name and DNA data

    Returns
    -------
    PolygenicScoreResponse
        Calculated score and interpretation

    Raises
    ------
    HTTPException
        If score calculation fails
    """
    try:
        # Parse DNA data from CSV string
        dna_df = pd.read_csv(io.StringIO(request.dna_data))

        # Calculate score
        calculator = PolygenicScoreCalculator()
        result = calculator.calculate_score(request.score_name, dna_df)

        return PolygenicScoreResponse(
            score_name=request.score_name,
            score=result["score"],
            interpretation=result.get("interpretation", "No interpretation available"),
            percentile=result.get("percentile"),
        )

    except pd.errors.ParserError as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Failed to parse DNA data: {str(e)}",
        )
    except KeyError as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Unknown polygenic score: {request.score_name}",
        )
    except Exception as e:
        logger.error(f"Error calculating polygenic score: {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error calculating score: {str(e)}",
        )


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8000)
